[latest]
title = "alookso ─ 둘러보기 ─ 최신 글"
url = "https://alook.so/discover/latest"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[trendiest]
title = "alookso ─ 둘러보기 ─ 뜨는 글"
url = "https://alook.so/discover"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user_alookso]
title = "alookso ─ alookso"
url = "https://alook.so/users/x4WtnB"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user_hyeseung]
title = "alookso ─ 정혜승 대표"
url = "https://alook.so/users/8OgtK8"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user_gwanyul]
title = "alookso ─ 천관율"
url = "https://alook.so/users/8letPq"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user_somewon]
title = "alookso ─ 윤성원"
url = "https://alook.so/users/8Ogtna"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user_showdam]
title = "alookso ─ 조소담"
url = "https://alook.so/users/qQPtde"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user_sooyoung]
title = "alookso ─ 윤수영"
url = "https://alook.so/users/xwVtDZ"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user_soventure]
title = "alookso ─ 이재웅"
url = "https://alook.so/users/6mt7oo"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user_yozoh]
title = "alookso ─ 신요조"
url = "https://alook.so/users/8Ogtd9"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user_janghyeyeong]
title = "alookso ─ 장혜영"
url = "https://alook.so/users/8XGtO0"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user_datacow]
title = "alookso ─ 데이터카우"
url = "https://alook.so/users/bA6tp1"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user_ohyeon]
title = "alookso ─ 권오현"
url = "https://alook.so/users/8YEtX8"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user_kwonsuengjun]
title = "alookso ─ 권승준"
url = "https://alook.so/users/q73t5E"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user_nobody]
title = "alookso ─ Nobody"
url = "https://alook.so/users/bzntNo"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

[user_taekie]
title = "alookso ─ 한상택"
url = "https://alook.so/users/73tAnn"
entrySelector = "div[class='flex-auto mt-2 space-y-2'] h5[class='font-medium text-break']"
titleSelector = "a"
linkSelector = "a"
waitUntil = "networkidle"
onFail = "stale"

